[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["cd php_broker && composer install --no-dev --optimize-autoloader"]

[start]
cmd = "cd php_broker && php broker.php start"
